
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Claudia
 */
public class GUI3 extends javax.swing.JFrame {
    double [][] ma = new double[5][5];
         double [][] mb = new double[5][5];
    /**
     * Creates new form GUI3
     */
    public GUI3() {
         initComponents();
         String matriz1 = "",matriz2="";
         int i = 0,j=0;
         double num;
        try {
            File datos = new File("Datos.txt");
            Scanner leer ;
            leer = new Scanner(datos);
            if(leer !=null){
            while(leer.hasNextDouble()){
                  for(int n =0 ; n < 5 ; n++){
                            for(int k =0 ; k < 5 ; k++){
                                    num= leer.nextDouble(); 
                                    if(i==0){
                                     matriz1+=num+"\t";
                                     ma[n][k]=num;
                                    }
                                    else{
                                        matriz2+=num+"\t";
                                        mb[n][k]=num;
                                    }
                            }
                             if(i==0)
                                     matriz1+="\n";
                                    else
                                        matriz2+="\n";
                    }
                    i++;
                   System.out.println();
            }}
                   leer.close();
                txtam1.setText(matriz1);
                txtam2.setText(matriz2);
        } catch (Exception ex) {
            Logger.getLogger(GUI3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtam2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtam1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtares = new javax.swing.JTextArea();
        btni = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        btnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtam2.setColumns(20);
        txtam2.setRows(5);
        jScrollPane1.setViewportView(txtam2);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        jLabel1.setText("Matrices");

        txtam1.setColumns(20);
        txtam1.setRows(5);
        jScrollPane2.setViewportView(txtam1);

        txtares.setColumns(20);
        txtares.setRows(5);
        jScrollPane3.setViewportView(txtares);

        btni.setText("Intersección");
        btni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniActionPerformed(evt);
            }
        });

        btnm.setText("Multiplicación");
        btnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmActionPerformed(evt);
            }
        });

        btnu.setText("Unión");
        btnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btni, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(445, Short.MAX_VALUE)
                    .addComponent(btnu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(436, 436, 436)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(btnu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuActionPerformed
        // TODO add your handling code here:
        double suma [][] = new double[5][5];
         suma = SumarMatrices(5,5,ma,mb);
         String sm="";
         for(int j =0 ; j < 5 ; j++){
                    for(int i =0 ; i < 5 ; i++){
                             sm += suma[j][i]+"\t";  
                    }
                  sm += "\n";
         }
         txtares.setText(sm);
        
    }//GEN-LAST:event_btnuActionPerformed

    private void btniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniActionPerformed
        // TODO add your handling code here:
        double inte [][] = new double[5][5];
         inte = InMatrices(5,5,ma,mb);
         String sm="";
         for(int j =0 ; j < 5 ; j++){
                    for(int i =0 ; i < 5 ; i++){
                             sm += inte[j][i]+"\t";  
                    }
                  sm += "\n";
         }
         txtares.setText(sm);
        
    }//GEN-LAST:event_btniActionPerformed

    private void btnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmActionPerformed
        // TODO add your handling code here:
        double mul [][] = new double[5][5];
         mul = MulMatrices(5,5,ma,mb);
         String sm="";
         for(int j =0 ; j < 5 ; j++){
                    for(int i =0 ; i < 5 ; i++){
                             sm += mul[j][i]+"\t";  
                    }
                  sm += "\n";
         }
         txtares.setText(sm);
        
          
    }//GEN-LAST:event_btnmActionPerformed
    public static double [][] MulMatrices(int x, int y, double [][] m1, double [][] m2){
                 double mul [][] = new double[x][y];
                    for(int i = 0 ; i < x ; i++){
                           for(int j = 0 ; j < y ; j++){
                                    mul[i][j] = m1[i][j] * m2[i][j];
                           }
                  }
                    return mul;
    }
    public static double [][] InMatrices(int x, int y, double [][] m1, double [][] m2){
                 double inte [][] = new double[x][y];
                    for(int i = 0 ; i < x ; i++){
                           for(int j = 0 ; j < y ; j++){
                                    if(m1[i][j]==m2[i][j])
                                            inte[i][j]= 1;
                                    else                
                                            inte[i][j]= 0;
                           }
                  }
                    return inte;
    }
    public static double [][] SumarMatrices(int x, int y, double [][] m1, double [][] m2){
                 double suma [][] = new double[x][y];
                    for(int i = 0 ; i < x ; i++){
                           for(int j = 0 ; j < y ; j++){
                                    suma[i][j] = m1[i][j] + m2[i][j];
                           }
                  }
                    return suma;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btni;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtam1;
    private javax.swing.JTextArea txtam2;
    private javax.swing.JTextArea txtares;
    // End of variables declaration//GEN-END:variables
}
