/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciogui4;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Claudia
 */
public class JfrPrincipal extends javax.swing.JFrame {
        Comperidor [] vectorObjetos = new Comperidor[10];
    /**
     * Creates new form JfrPrincipal
     */
    public JfrPrincipal() {
        initComponents();
        String linea,tabla="";
        int c =0,i =0;
        try {
            BufferedReader br = new BufferedReader(new FileReader("Datos.txt"));
            linea = br.readLine();
            while(linea!= null){
                  int id=0, edad=0, mes=0, gene=0;
                StringTokenizer st = new StringTokenizer(linea);
                while(st.hasMoreTokens()){
                           switch(c%4){
                                    case 0:
                                             id = Integer.parseInt(st.nextToken());
                                             break;
                                    case 1:
                                             edad =  Integer.parseInt(st.nextToken());
                                             break;
                                    case 2:
                                             mes =  Integer.parseInt(st.nextToken());
                                             break;
                                    case 3 :
                                            gene =  Integer.parseInt(st.nextToken());
                                             break;
                           }
                           c++;
                   }
                   c =0;
                   vectorObjetos[i] = new Comperidor(id,edad,mes,gene);
                  System.out.println(vectorObjetos[i].toString());
                  tabla += vectorObjetos[i].toString()+"\n";
                  i++;
                  linea = br.readLine();
            }
            txacomp.setText(tabla);
            br.close();
        } catch (Exception ex) {
            Logger.getLogger(JfrPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txacomp = new javax.swing.JTextArea();
        btnpaq = new javax.swing.JButton();
        btncat = new javax.swing.JButton();
        lblmayor = new javax.swing.JLabel();
        cmbcat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txacomp.setColumns(20);
        txacomp.setRows(5);
        jScrollPane1.setViewportView(txacomp);

        btnpaq.setText("Paquetes");
        btnpaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaqActionPerformed(evt);
            }
        });

        btncat.setText("Categoria");
        btncat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatActionPerformed(evt);
            }
        });

        cmbcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costo inscripción marzo", "Costo inscripción abril", "Costo inscripción mayo" }));
        cmbcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpaq, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btncat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnpaq, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cmbcat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblmayor, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatActionPerformed
        // TODO add your handling code here:
        String tabla ="";
        for(int i = 0 ; i < 10 ; i ++){
                  tabla += "Competirdor  :  "+vectorObjetos[i].getid()+" \tCategoria  :  "+vectorObjetos[i].Categoria()+"\n";
        }
        
        txacomp.setText(tabla);
    }//GEN-LAST:event_btncatActionPerformed

    private void btnpaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaqActionPerformed
        // TODO add your handling code here:
            int [][] catego = new int[2][12];
            int c=0,mayor =0,xm = 0,ym = 0,mes,menor = 6000,xme=0,yme=0;
            String cmay = "",cmen="";
            String tabla = "\t\t Paquetes a Entregar por categoria \n\n";
            for(int i = 0 ; i < 10 ; i ++){
                   for(int j = 0 ; j < 2 ; j++){
                       for(int k = 0 ; k < 12 ; k++){
                                   c = vectorObjetos[i].getcatego(j, k);
                                   catego[j][k] += c;
                                   if(catego[j][k] > mayor){
                                    xm = j;  
                                    ym = k;
                                   }
                                    mes = vectorObjetos[i].getMes()*catego[j][k];
                                   if(mes < menor ){
                                    xme = j;  
                                    yme = k;
                                   }
                       }
                  }
         }
         
         tabla += "AV  :  "+catego[0][0]+"\tAF : "+catego[1][0]+"\n" ;
         tabla += "BV  :  "+catego[0][1]+"\tBF : "+catego[1][1]+"\n" ;
         tabla += "CV  :  "+catego[0][2]+"\tCF : "+catego[1][2]+"\n" ;
         tabla += "DV  :  "+catego[0][3]+"\tDF : "+catego[1][3]+"\n" ;
         tabla += "EV  :  "+catego[0][4]+"\tEF : "+catego[1][4]+"\n" ;
         tabla += "FV  :  "+catego[0][5]+"\tFF : "+catego[1][5]+"\n" ;
         tabla += "GV  :  "+catego[0][6]+"\tGF : "+catego[1][6]+"\n" ;
         tabla += "HV  :  "+catego[0][7]+"\tHF :  "+catego[1][7]+"\n" ;
         tabla += "IV   :  "+catego[0][8]+"\tIF   :  "+catego[1][8]+"\n" ;
         tabla += "JV  :  "+catego[0][9]+"\tJF : "+catego[1][9]+"\n" ;
         tabla += "KV  :  "+catego[0][10]+"\tKF : "+catego[1][10]+"\n" ;
         tabla += "LV  :  "+catego[0][11]+"\tLF : "+catego[1][11]+"\n" ;
         
         switch(ym){
                  case 0:
                           cmay = "A";
                           break;
                  case 1:
                           cmay = "B";
                           break;
                  case 2:
                           cmay = "C";
                           break;
                  case 3:
                           cmay = "D";
                           break;
                  case 4:
                           cmay = "E";
                           break;
                   case 5:
                           cmay = "F";
                           break;
                  case 6:
                           cmay = "G";
                           break;
                  case 7:
                           cmay = "H";
                           break;
                  case 8:
                           cmay = "I";
                           break;
                  case 9:
                           cmay = "J";
                           break;
                  case 10:
                           cmay = "k";
                           break;
                  case 11:
                           cmay = "L";
                           break;
         }
         switch(xm){
                  case 0:
                           cmay += "V";
                           break;
                  case 1:
                           cmay += "F";
                           break;
         }
         switch(yme){
                  case 0:
                           cmen = "A";
                           break;
                  case 1:
                           cmen = "B";
                           break;
                  case 2:
                          cmen = "C";
                           break;
                  case 3:
                           cmen = "D";
                           break;
                  case 4:
                           cmen = "E";
                           break;
                   case 5:
                          cmen = "F";
                           break;
                  case 6:
                           cmen = "G";
                           break;
                  case 7:
                           cmen = "H";
                           break;
                  case 8:
                           cmen = "I";
                           break;
                  case 9:
                           cmen = "J";
                           break;
                  case 10:
                           cmen = "k";
                           break;
                  case 11:
                           cmen = "L";
                           break;
         }
         switch(xme){
                  case 0:
                           cmen += "V";
                           break;
                  case 1:
                           cmen += "F";
                           break;
         }
         lblmayor.setText("Categoria con más inscritos : "+cmay+"\tCategoria con menos recaudado   : "+cmen);
        txacomp.setText(tabla);
    }//GEN-LAST:event_btnpaqActionPerformed

    private void cmbcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcatActionPerformed
        // TODO add your handling code here:
        int sel = cmbcat.getSelectedIndex();
        int selemes= 0,c=0,costoi=0;
        String mes ="",menor="";
        int c3=0, c4= 0, c5 = 0;
        int cat3,cat4,cat5;
        switch(sel){
            case 0 :
                selemes = 3;
                mes = "marzo";
                costoi = 295;
               break;
            case 1:
                selemes = 4;
                mes = "abril";
                costoi =345;
                break;
            case 2:
                selemes= 5;
                mes = "mayo";
                costoi = 395;
                break;
        }
        
        for(int i = 0 ; i < 10 ; i ++){
                   if(vectorObjetos[i].getMes() == selemes ){
                       c++;
                   }
        }
        
        for(int i = 0 ; i < 10 ; i ++){
                  switch(vectorObjetos[i].getMes()){
                        case 3 :
                            c3++;
                           break;
                        case 4:
                            c4++;
                            break;
                        case 5:
                            c5++;
                            break;
                    }
        }
        cat3 = c3 * 295;
        cat4 = c4 * 345;
        cat5 = c5 * 395;
         if(cat3 < cat4 && cat3 < cat5)
                   menor = "marzo";
         if(cat4 < cat3 && cat4 < cat5)
                   menor = "abril";
         if(cat5 < cat4 && cat5 < cat3)
                   menor = "mayo";
        
         lblmayor.setText(lblmayor.getText()+"\tMes con menos recaudado : "+menor);
        txacomp.setText("En el mes "+mes+" se recaudó :  "+costoi*c);
    }//GEN-LAST:event_cmbcatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncat;
    private javax.swing.JButton btnpaq;
    private javax.swing.JComboBox<String> cmbcat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmayor;
    private javax.swing.JTextArea txacomp;
    // End of variables declaration//GEN-END:variables
}
